name: release
on:
    push:
        tags: v[0-9]+.[0-9]+.[0-9]+
jobs:
    release:
        name: 'release: ${{github.ref_name}}'
        runs-on: ubuntu-latest
        steps:
            - name: clone repository
              uses: actions/checkout@v4
            - name: dispatch release
              uses: softprops/action-gh-release@v2
              with:
                generate_release_notes: true